name: commit-checks
on: [ push ]

jobs:
  check:
    runs-on: ubuntu-latest  
    steps:
    - name: Checkout  
      uses: actions/checkout@v4

    - name: Install toolchain
      run: rustup update stable && rustup default stable

    - name: Run cargo check
      run: cargo check  

    - name: Run cargo build
      run: cargo build  

    - name: Run tests
      run: cargo test